### Create a Product (Admin: alice)
POST http://localhost:4004/odata/v4/inventory/Product
Content-Type: application/json
Authorization: Basic alice:alice

{
  "Name": "Microchip Monitor",
  "UnitPrice": 150.0,
  "Quantity": 40
}

### Get All Products (User: bob)
GET http://localhost:4004/odata/v4/inventory/Product
Accept: application/json
Authorization: Basic bob:bob

### Get a Product by ID (User: bob)
GET http://localhost:4004/odata/v4/inventory/Product(ID='0305c14a-867b-412a-83db-df98faab5896')
Accept: application/json
Authorization: Basic bob:bob

### Update a Product (Admin: alice)
PATCH http://localhost:4004/odata/v4/inventory/Product(ID='0305c14a-867b-412a-83db-df98faab5896')
Content-Type: application/json
Authorization: Basic alice:alice

{
  "Name": "34 inch Ryzen Monitor",
  "UnitPrice": 201.0,
  "Quantity": 60
}

### Delete a Product (Admin: alice)
DELETE http://localhost:4004/odata/v4/inventory/Product(ID='product-id')
Authorization: Basic alice:alice

### Create an Order (User: bob)
POST http://localhost:4004/odata/v4/inventory/Order
Content-Type: application/json
Authorization: Basic bob:bob

{
  "Company_ID": "4736f281-41c9-42de-b2ae-7f7c2c2802dc",
  "Items": [
    {
      "Product_ID": "d00e74e2-0b96-44c5-aed6-748332aea2e6",
      "Quantity": 5
    }
  ]
}

### Get All Orders (User: bob)
GET http://localhost:4004/odata/v4/inventory/Order
Accept: application/json
Authorization: Basic bob:bob

### Get Order by ID (User: bob)
GET http://localhost:4004/odata/v4/inventory/Order(ID='order-id')
Accept: application/json
Authorization: Basic bob:bob

### Transaction handling request (valid)

POST http://localhost:4004/odata/v4/inventory/submitOrder
Content-Type: application/json
Authorization: Basic bob:bob

{
  "companyId": "29650449-eefe-457f-a55d-7d3d33eb3673",
  "items": [
    {
      "productId": "0fcc608f-d121-4a30-ac36-bab10cd348bf",
      "quantity": 5
    }
  ]
}

### Transaction handling request (Invalid)


POST http://localhost:4004/odata/v4/inventory/submitOrder
Content-Type: application/json
Authorization: Basic bob:bob

{
  "companyId": "63ad9cab-1aa0-4c7f-9f7d-68efb9ddcc6f",
  "items": [
    {
      "productId": "559ad5cc-f136-4738-a64e-d95d77bdb9fe",
      "quantity": 99999
        }
  ]
}
### Cancel Order Test for transaction handle

POST http://localhost:4004/odata/v4/inventory/cancelOrder
Content-Type: application/json
Authorization: Basic alice:admin

{
  "orderId": "4c65969d-c74e-4e07-81e4-411b0cf9936d"
}

### Verify Product Stock After Cancellation
GET http://localhost:4004/odata/v4/inventory/Product(ID='559ad5cc-f136-4738-a64e-d95d77bdb9fe')
Authorization: Basic alice:admin
### Create a Company (Admin: alice)
POST http://localhost:4004/odata/v4/inventory/Company
Content-Type: application/json
Authorization: Basic alice:alice

{
  "Name": "MOYOTECH",
  "Address": "123 Main Street"
}

### Get All Notifications (User: bob)
GET http://localhost:4004/odata/v4/notifications/Notifications
Accept: application/json
Authorization: Basic bob:bob